![JB](https://avatars2.githubusercontent.com/u/10920646?s=400&u=eeb896367e071a7661c130c0115815106ec583e7&v=4)
name: AAS
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-minimal
title: Awesome Automation Stories
description: Joe Blaauw, System Engineer, PowerShell lover, blogging about cool stuff I come accros with.
