name: BAAS
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-cayman
avatar: https://static.pexels.com/photos/546819/pexels-photo-546819.jpeg
title: "Awesome Automation Stories"
description: Joe Blaauw, PowerShell Developer, DevOps.
linkedin: jeroen-blaauw-9b0b522
